# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_ROCKCHIP) += \
	rv1108-evb.dtb \
	rk3036-evb.dtb \
	rk3036-kylin.dtb \
	rk3066a-bqcurie2.dtb \
	rk3066a-marsboard.dtb \
	rk3066a-mk808.dtb \
	rk3066a-rayeager.dtb \
	rk3188-px3-evb.dtb \
	rk3188-radxarock.dtb \
	rk3228-evb.dtb \
	rk3229-evb.dtb \
	rk3288-evb-act8846.dtb \
	rk3288-evb-rk808.dtb \
	rk3288-fennec.dtb \
	rk3288-firefly-beta.dtb \
	rk3288-firefly.dtb \
	rk3288-firefly-reload.dtb \
	rk3288-miqi.dtb \
	rk3288-phycore-rdk.dtb \
	rk3288-popmetal.dtb \
	rk3288-r89.dtb \
	rk3288-rock2-square.dtb \
	rk3288-tinker.dtb \
	rk3288-tinker-s.dtb \
	rk3288-veyron-brain.dtb \
	rk3288-veyron-jaq.dtb \
	rk3288-veyron-jerry.dtb \
	rk3288-veyron-mickey.dtb \
	rk3288-veyron-minnie.dtb \
	rk3288-veyron-pinky.dtb \
	rk3288-veyron-speedy.dtb \
	rk3288-vyasa.dtb
