# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_ASPEED) += \
	aspeed-ast2500-evb.dtb \
	aspeed-bmc-arm-centriq2400-rep.dtb \
	aspeed-bmc-arm-stardragon4800-rep2.dtb \
	aspeed-bmc-facebook-tiogapass.dtb \
	aspeed-bmc-intel-s2600wf.dtb \
	aspeed-bmc-opp-lanyang.dtb \
	aspeed-bmc-opp-palmetto.dtb \
	aspeed-bmc-opp-romulus.dtb \
	aspeed-bmc-opp-witherspoon.dtb \
	aspeed-bmc-opp-zaius.dtb \
	aspeed-bmc-portwell-neptune.dtb \
	aspeed-bmc-quanta-q71l.dtb
