#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2020 Christian Brauner.  All Rights Reserved.
#
# FS QA Test 622
#
# Test that idmapped mounts behave correctly.
#
seq=`basename $0`
seqres=$RESULT_DIR/$seq
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
	cd /
	rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common/rc
. ./common/filter

# remove previous $seqres.full before test
rm -f $seqres.full

# real QA test starts here

# Modify as appropriate.
_supported_fs ext4 xfs
_require_idmapped_mounts
_require_test

echo "Silence is golden"

$here/src/idmapped-mounts/idmapped-mounts --device "$TEST_DEV" --mount "$TEST_DIR" --fstype "$FSTYP"

status=$?
exit
