#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2021 Christian Brauner.  All Rights Reserved.
#
# FS QA Test 651
#
# Test that setattr works correctly.
#
. ./common/preamble
_begin_fstest auto attr cap idmapped mount perms

# Import common functions.
. ./common/filter

# real QA test starts here

_supported_fs generic
_require_idmapped_mounts
_require_test

echo "Silence is golden"

$here/src/idmapped-mounts/idmapped-mounts --test-setattr-fix \
	--device "$TEST_DEV" --mount "$TEST_DIR" --fstype "$FSTYP"

status=$?
exit
