# SPDX-License-Identifier: GPL-2.0-only
userprogs-always-y += \
	alg-hash \
	alg-encrypt \
	splice-out \
	tcp-send \
	tcp-sink \
	tls-send \
	tls-sink \
	udp-send \
	udp-sink \
	unix-send \
	unix-sink
