# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_SOC_IMX1) += \
	imx1-ads.dtb \
	imx1-apf9328.dtb
dtb-$(CONFIG_SOC_IMX25) += \
	imx25-eukrea-mbimxsd25-baseboard.dtb \
	imx25-eukrea-mbimxsd25-baseboard-cmo-qvga.dtb \
	imx25-eukrea-mbimxsd25-baseboard-dvi-svga.dtb \
	imx25-eukrea-mbimxsd25-baseboard-dvi-vga.dtb \
	imx25-karo-tx25.dtb \
	imx25-pdk.dtb
dtb-$(CONFIG_SOC_IMX27) += \
	imx27-apf27.dtb \
	imx27-apf27dev.dtb \
	imx27-eukrea-mbimxsd27-baseboard.dtb \
	imx27-pdk.dtb \
	imx27-phytec-phycore-rdk.dtb \
	imx27-phytec-phycard-s-rdk.dtb
dtb-$(CONFIG_SOC_IMX31) += \
	imx31-bug.dtb \
	imx31-lite.dtb
dtb-$(CONFIG_SOC_IMX35) += \
	imx35-eukrea-mbimxsd35-baseboard.dtb \
	imx35-pdk.dtb
dtb-$(CONFIG_SOC_IMX50) += \
	imx50-evk.dtb
dtb-$(CONFIG_SOC_IMX51) += \
	imx51-apf51.dtb \
	imx51-apf51dev.dtb \
	imx51-babbage.dtb \
	imx51-digi-connectcore-jsk.dtb \
	imx51-eukrea-mbimxsd51-baseboard.dtb \
	imx51-ts4800.dtb \
	imx51-zii-rdu1.dtb \
	imx51-zii-scu2-mezz.dtb \
	imx51-zii-scu3-esb.dtb
dtb-$(CONFIG_SOC_IMX53) += \
	imx53-ard.dtb \
	imx53-cx9020.dtb \
	imx53-kp-ddc.dtb \
	imx53-kp-hsc.dtb \
	imx53-m53evk.dtb \
	imx53-mba53.dtb \
	imx53-ppd.dtb \
	imx53-qsb.dtb \
	imx53-qsrb.dtb \
	imx53-smd.dtb \
	imx53-tx53-x03x.dtb \
	imx53-tx53-x13x.dtb \
	imx53-usbarmory.dtb \
	imx53-voipac-bsb.dtb
dtb-$(CONFIG_SOC_IMX6Q) += \
	imx6dl-apf6dev.dtb \
	imx6dl-aristainetos_4.dtb \
	imx6dl-aristainetos_7.dtb \
	imx6dl-aristainetos2_4.dtb \
	imx6dl-aristainetos2_7.dtb \
	imx6dl-colibri-eval-v3.dtb \
	imx6dl-cubox-i.dtb \
	imx6dl-cubox-i-emmc-som-v15.dtb \
	imx6dl-cubox-i-som-v15.dtb \
	imx6dl-dfi-fs700-m60.dtb \
	imx6dl-gw51xx.dtb \
	imx6dl-gw52xx.dtb \
	imx6dl-gw53xx.dtb \
	imx6dl-gw54xx.dtb \
	imx6dl-gw551x.dtb \
	imx6dl-gw552x.dtb \
	imx6dl-gw553x.dtb \
	imx6dl-gw560x.dtb \
	imx6dl-gw5903.dtb \
	imx6dl-gw5904.dtb \
	imx6dl-hummingboard.dtb \
	imx6dl-hummingboard-emmc-som-v15.dtb \
	imx6dl-hummingboard-som-v15.dtb \
	imx6dl-hummingboard2.dtb \
	imx6dl-hummingboard2-emmc-som-v15.dtb \
	imx6dl-hummingboard2-som-v15.dtb \
	imx6dl-icore.dtb \
	imx6dl-icore-mipi.dtb \
	imx6dl-icore-rqs.dtb \
	imx6dl-mamoj.dtb \
	imx6dl-nit6xlite.dtb \
	imx6dl-nitrogen6x.dtb \
	imx6dl-phytec-mira-rdk-nand.dtb \
	imx6dl-phytec-pbab01.dtb \
	imx6dl-rex-basic.dtb \
	imx6dl-riotboard.dtb \
	imx6dl-sabreauto.dtb \
	imx6dl-sabrelite.dtb \
	imx6dl-sabresd.dtb \
	imx6dl-savageboard.dtb \
	imx6dl-ts4900.dtb \
	imx6dl-ts7970.dtb \
	imx6dl-tx6dl-comtft.dtb \
	imx6dl-tx6s-8034.dtb \
	imx6dl-tx6s-8034-mb7.dtb \
	imx6dl-tx6s-8035.dtb \
	imx6dl-tx6s-8035-mb7.dtb \
	imx6dl-tx6u-801x.dtb \
	imx6dl-tx6u-80xx-mb7.dtb \
	imx6dl-tx6u-8033.dtb \
	imx6dl-tx6u-8033-mb7.dtb \
	imx6dl-tx6u-811x.dtb \
	imx6dl-tx6u-81xx-mb7.dtb \
	imx6dl-udoo.dtb \
	imx6dl-wandboard.dtb \
	imx6dl-wandboard-revb1.dtb \
	imx6dl-wandboard-revd1.dtb \
	imx6q-apalis-eval.dtb \
	imx6q-apalis-ixora.dtb \
	imx6q-apalis-ixora-v1.1.dtb \
	imx6q-apf6dev.dtb \
	imx6q-arm2.dtb \
	imx6q-b450v3.dtb \
	imx6q-b650v3.dtb \
	imx6q-b850v3.dtb \
	imx6q-cm-fx6.dtb \
	imx6q-cubox-i.dtb \
	imx6q-cubox-i-emmc-som-v15.dtb \
	imx6q-cubox-i-som-v15.dtb \
	imx6q-dfi-fs700-m60.dtb \
	imx6q-dhcom-pdk2.dtb \
	imx6q-display5-tianma-tm070-1280x768.dtb \
	imx6q-dmo-edmqmx6.dtb \
	imx6q-dms-ba16.dtb \
	imx6q-evi.dtb \
	imx6q-gk802.dtb \
	imx6q-gw51xx.dtb \
	imx6q-gw52xx.dtb \
	imx6q-gw53xx.dtb \
	imx6q-gw5400-a.dtb \
	imx6q-gw54xx.dtb \
	imx6q-gw551x.dtb \
	imx6q-gw552x.dtb \
	imx6q-gw553x.dtb \
	imx6q-gw560x.dtb \
	imx6q-gw5903.dtb \
	imx6q-gw5904.dtb \
	imx6q-h100.dtb \
	imx6q-hummingboard.dtb \
	imx6q-hummingboard-emmc-som-v15.dtb \
	imx6q-hummingboard-som-v15.dtb \
	imx6q-hummingboard2.dtb \
	imx6q-hummingboard2-emmc-som-v15.dtb \
	imx6q-hummingboard2-som-v15.dtb \
	imx6q-icore.dtb \
	imx6q-icore-mipi.dtb \
	imx6q-icore-ofcap10.dtb \
	imx6q-icore-ofcap12.dtb \
	imx6q-icore-rqs.dtb \
	imx6q-kp-tpc.dtb \
	imx6q-marsboard.dtb \
	imx6q-mccmon6.dtb \
	imx6q-nitrogen6x.dtb \
	imx6q-nitrogen6_max.dtb \
	imx6q-nitrogen6_som2.dtb \
	imx6q-novena.dtb \
	imx6q-phytec-mira-rdk-emmc.dtb \
	imx6q-phytec-mira-rdk-nand.dtb \
	imx6q-phytec-pbab01.dtb \
	imx6q-pistachio.dtb \
	imx6q-rex-pro.dtb \
	imx6q-sabreauto.dtb \
	imx6q-sabrelite.dtb \
	imx6q-sabresd.dtb \
	imx6q-savageboard.dtb \
	imx6q-sbc6x.dtb \
	imx6q-tbs2910.dtb \
	imx6q-ts4900.dtb \
	imx6q-ts7970.dtb \
	imx6q-tx6q-1010.dtb \
	imx6q-tx6q-1010-comtft.dtb \
	imx6q-tx6q-1020.dtb \
	imx6q-tx6q-1020-comtft.dtb \
	imx6q-tx6q-1036.dtb \
	imx6q-tx6q-1036-mb7.dtb \
	imx6q-tx6q-10x0-mb7.dtb \
	imx6q-tx6q-1110.dtb \
	imx6q-tx6q-11x0-mb7.dtb \
	imx6q-udoo.dtb \
	imx6q-utilite-pro.dtb \
	imx6q-var-dt6customboard.dtb \
	imx6q-wandboard.dtb \
	imx6q-wandboard-revb1.dtb \
	imx6q-wandboard-revd1.dtb \
	imx6q-zii-rdu2.dtb \
	imx6qp-nitrogen6_max.dtb \
	imx6qp-nitrogen6_som2.dtb \
	imx6qp-phytec-mira-rdk-nand.dtb \
	imx6qp-sabreauto.dtb \
	imx6qp-sabresd.dtb \
	imx6qp-tx6qp-8037.dtb \
	imx6qp-tx6qp-8037-mb7.dtb \
	imx6qp-tx6qp-8137.dtb \
	imx6qp-tx6qp-8137-mb7.dtb \
	imx6qp-wandboard-revd1.dtb \
	imx6qp-zii-rdu2.dtb
dtb-$(CONFIG_SOC_IMX6SL) += \
	imx6sl-evk.dtb \
	imx6sl-warp.dtb
dtb-$(CONFIG_SOC_IMX6SLL) += \
	imx6sll-evk.dtb
dtb-$(CONFIG_SOC_IMX6SX) += \
	imx6sx-nitrogen6sx.dtb \
	imx6sx-sabreauto.dtb \
	imx6sx-sdb-reva.dtb \
	imx6sx-sdb-sai.dtb \
	imx6sx-sdb.dtb \
	imx6sx-softing-vining-2000.dtb \
	imx6sx-udoo-neo-basic.dtb \
	imx6sx-udoo-neo-extended.dtb \
	imx6sx-udoo-neo-full.dtb
dtb-$(CONFIG_SOC_IMX6UL) += \
	imx6ul-14x14-evk.dtb \
	imx6ul-ccimx6ulsbcexpress.dtb \
	imx6ul-ccimx6ulsbcpro.dtb \
	imx6ul-geam.dtb \
	imx6ul-isiot-emmc.dtb \
	imx6ul-isiot-nand.dtb \
	imx6ul-liteboard.dtb \
	imx6ul-opos6uldev.dtb \
	imx6ul-pico-hobbit.dtb \
	imx6ul-tx6ul-0010.dtb \
	imx6ul-tx6ul-0011.dtb \
	imx6ul-tx6ul-mainboard.dtb \
	imx6ull-14x14-evk.dtb \
	imx6ull-colibri-eval-v3.dtb \
	imx6ull-colibri-wifi-eval-v3.dtb \
	imx6ulz-14x14-evk.dtb
dtb-$(CONFIG_SOC_IMX7D) += \
	imx7d-cl-som-imx7.dtb \
	imx7d-colibri-emmc-eval-v3.dtb \
	imx7d-colibri-eval-v3.dtb \
	imx7d-nitrogen7.dtb \
	imx7d-pico-pi.dtb \
	imx7d-sbc-imx7.dtb \
	imx7d-sdb.dtb \
	imx7d-sdb-sht11.dtb \
	imx7s-colibri-eval-v3.dtb \
	imx7s-warp.dtb
