# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_SPEAR13XX) += \
	spear1310-evb.dtb \
	spear1340-evb.dtb
dtb-$(CONFIG_ARCH_SPEAR3XX) += \
	spear300-evb.dtb \
	spear310-evb.dtb \
	spear320-evb.dtb \
	spear320-hmi.dtb
dtb-$(CONFIG_ARCH_SPEAR6XX) += \
	spear600-evb.dtb
