# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_QCOM) += \
	qcom-apq8060-dragonboard.dtb \
	qcom-apq8064-arrow-sd-600eval.dtb \
	qcom-apq8064-cm-qs600.dtb \
	qcom-apq8064-ifc6410.dtb \
	qcom-apq8064-sony-xperia-yuga.dtb \
	qcom-apq8064-asus-nexus7-flo.dtb \
	qcom-apq8074-dragonboard.dtb \
	qcom-apq8084-ifc6540.dtb \
	qcom-apq8084-mtp.dtb \
	qcom-ipq4019-ap.dk01.1-c1.dtb \
	qcom-ipq4019-ap.dk04.1-c1.dtb \
	qcom-ipq4019-ap.dk04.1-c3.dtb \
	qcom-ipq4019-ap.dk07.1-c1.dtb \
	qcom-ipq4019-ap.dk07.1-c2.dtb \
	qcom-ipq8064-ap148.dtb \
	qcom-msm8660-surf.dtb \
	qcom-msm8960-cdp.dtb \
	qcom-msm8974-fairphone-fp2.dtb \
	qcom-msm8974-lge-nexus5-hammerhead.dtb \
	qcom-msm8974-samsung-klte.dtb \
	qcom-msm8974-sony-xperia-amami.dtb \
	qcom-msm8974-sony-xperia-castor.dtb \
	qcom-msm8974-sony-xperia-honami.dtb \
	qcom-mdm9615-wp8548-mangoh-green.dtb
