# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_S3C24XX) += \
	s3c2416-smdk2416.dtb
dtb-$(CONFIG_ARCH_S3C64XX) += \
	s3c6410-mini6410.dtb \
	s3c6410-smdk6410.dtb
dtb-$(CONFIG_ARCH_S5PV210) += \
	s5pv210-aquila.dtb \
	s5pv210-fascinate4g.dtb \
	s5pv210-galaxys.dtb \
	s5pv210-goni.dtb \
	s5pv210-smdkc110.dtb \
	s5pv210-smdkv210.dtb \
	s5pv210-torbreck.dtb
