# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for SPI HID tarnsport drivers
#

obj-$(CONFIG_SPI_HID_APPLE_CORE)		+= spi-hid-apple.o

spi-hid-apple-objs				=  spi-hid-apple-core.o

obj-$(CONFIG_SPI_HID_APPLE_OF)			+= spi-hid-apple-of.o
