#ifndef __DT_ASM_H__
#define __DT_ASM_H__

#define MSM_FRONTEND_DAI_MULTIMEDIA1	0
#define MSM_FRONTEND_DAI_MULTIMEDIA2	1
#define	MSM_FRONTEND_DAI_MULTIMEDIA3	2
#define MSM_FRONTEND_DAI_MULTIMEDIA4	3
#define MSM_FRONTEND_DAI_MULTIMEDIA5	4
#define MSM_FRONTEND_DAI_MULTIMEDIA6	5
#define	MSM_FRONTEND_DAI_MULTIMEDIA7	6
#define	MSM_FRONTEND_DAI_MULTIMEDIA8	7

#endif
