# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_UNIPHIER) += \
	uniphier-ld4-ref.dtb \
	uniphier-ld6b-ref.dtb \
	uniphier-pro4-ace.dtb \
	uniphier-pro4-ref.dtb \
	uniphier-pro4-sanji.dtb \
	uniphier-pxs2-gentil.dtb \
	uniphier-pxs2-vodka.dtb \
	uniphier-sld8-ref.dtb
