# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_MEDIATEK) += \
	mt2701-evb.dtb \
	mt6580-evbp1.dtb \
	mt6589-aquaris5.dtb \
	mt6592-evb.dtb \
	mt7623a-rfb-emmc.dtb \
	mt7623a-rfb-nand.dtb \
	mt7623n-rfb-emmc.dtb \
	mt7623n-bananapi-bpi-r2.dtb \
	mt8127-moose.dtb \
	mt8135-evbp1.dtb
